apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta
  namespace: censer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delta
  template:
    metadata:
      labels:
        app: delta
    spec:
      containers:
        - name: delta
          image: censer-delta:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 14702
          volumeMounts:
            - name: config
              mountPath: /home/rust/src/Revolt.overrides.toml
              subPath: Revolt.overrides.toml
      volumes:
        - name: config
          configMap:
            name: censer-config
---
apiVersion: v1
kind: Service
metadata:
  name: delta
  namespace: censer
spec:
  type: NodePort
  selector:
    app: delta
  ports:
    - port: 14702
      targetPort: 14702
      nodePort: 30702
