name: Feature Request
description: Propose a user-facing Stoat improvement
title: "[Feature]: "
labels: ["feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Start with the user problem and expected outcome.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Messaging
        - Voice/Video
        - Search/Discovery
        - Moderation/Admin
        - Performance
        - Accessibility
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user problem are you trying to solve?
      placeholder: Currently, when users try to..., they cannot...
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Desired Outcome
      description: What should improve if this is implemented?
      placeholder: Users should be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred implementation and UX behavior.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives were considered and why are they less suitable?
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List clear criteria for completion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (reporter perspective)
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Scope and Impact
      description: Who is impacted and how often?
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: Supporting Context
      description: Mockups, screenshots, links, and comparable behavior in other products.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched for existing duplicate issues.
          required: true
        - label: I described the user problem and desired outcome.
          required: true
        - label: I included acceptance criteria and impact.
          required: true
