[database]
mongodb = "mongodb://mongodb:27017"
redis = "redis://redis:6379/"

[rabbit]
host = "rabbitmq"

[hosts]
app = "http://localhost:5173"
api = "http://localhost:14702"
events = "ws://localhost:14703"
autumn = "http://localhost:14704"
january = "http://localhost:14705"
voso_legacy = ""
voso_legacy_ws = ""

[hosts.livekit]
worldwide = ""

[api]

[api.smtp]
host = "maildev"
username = "smtp"
password = "smtp"
from_address = "development@stoat.chat"
reply_to = "support@stoat.chat"
port = 25
use_tls = false
use_starttls = false

[api.livekit]

[files.s3]
endpoint = "http://minio:9000"
region = "minio"
access_key_id = "minioautumn"
secret_access_key = "minioautumn"
default_bucket = "revolt-uploads"
path_style_buckets = true
