FROM archlinux:base
RUN pacman -Sy --noconfirm ca-certificates openssl && pacman -Scc --noconfirm
WORKDIR /home/rust/src
COPY revolt-bonfire /usr/local/bin/server
ENV ROCKET_ADDRESS=0.0.0.0
CMD ["server"]
